name: SealLang test

on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cmake -B build -S .
    - run: cmake --build build
    - run: ctest --test-dir build